# Referencias

## Artículos

Los artículos están ordenados por fecha de aparición (o actualización), del más reciente al más antiguo: 
  
- [Top 45 Data Science Interview Questions You Must Prepare In 2019](https://www.edureka.co/blog/interview-questions/data-science-interview-questions/).   
Autor: [Sandeep Dayananda](https://www.edureka.co/blog/author/sandeepdedureka-co/).  
Fecha: 2019-05-22.  

- [Top 30 data science interview questions](https://towardsdatascience.com/top-30-data-science-interview-questions-7dd9a96d3f5c). 
Nota: En realidad son 31 preguntas.
Autor: [Nitin Panwar](https://towardsdatascience.com/@nitinpanwar98).  
Fecha: 2018-12-31.  
  
- [109 Data Science Interview Questions and Answers](https://www.springboard.com/blog/data-science-interview-questions/).  
Nota: Además de las preguntas planteadas en el artículo también aporta varios enlaces a otros listados de preguntas de temáticas más específicas (R, Python, Data Mining, etc.). En realidad son "sólo" 93 preguntas.
Autor: Michael Rundell.  
Fecha: 2018-11-29.  
  
- [120 Data Science Interview Questions](https://github.com/kojino/120-Data-Science-Interview-Questions).   
Autor: [Kojino](https://github.com/kojino)  
Fecha: 2018-03-18.  
  
- [21 Must-Know Data Science Interview Questions and Answers](https://www.kdnuggets.com/2016/02/21-data-science-interview-questions-answers.html).  
Autor:  [Gregory Piatetsky](https://www.kdnuggets.com/author/gregory-piatetsky).  
Fecha: 2016-02-21.  
  
- [20 Questions to Detect Fake Data Scientists](https://www.import.io/post/20-questions-to-detect-fake-data-scientists/).  
Autor: [Andrew Fogg](https://www.import.io/).  
Fecha: 2015-12-17.  
  

  
## Libros y otros recursos

- [Data Science Cheatsheet](https://github.com/ml874/Data-Science-Cheatsheet). Autor: [Maverick Lin](https://github.com/ml874/Data-Science-Cheatsheet).  
- [Documentación de scikit-learn](https://scikit-learn.org/stable/modules/clustering.html).  



